<a href="https://colab.research.google.com/github/AryanRaut14/BreastCancerDetection/blob/main/BreastCancerPytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [15]:
df = pd.read_csv('https://raw.githubusercontent.com/AryanRaut14/BreastCancerDetection/main/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [16]:
df.shape

(569, 33)

In [17]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [18]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Train Test Split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Scaling

In [20]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [21]:
x_train

array([[ 1.05499328,  0.33598642,  1.01964273, ...,  1.24360655,
         0.25181691,  0.0410636 ],
       [-0.45438334, -0.19822337, -0.51383784, ..., -1.6018131 ,
        -0.68632489, -1.10762536],
       [ 1.77480689, -0.34714025,  1.62948094, ...,  1.07163959,
        -0.27219022,  0.26226383],
       ...,
       [-1.48444221, -1.08699718, -1.36357266, ..., -1.01217761,
        -1.11060163,  1.33666499],
       [ 0.31006988, -0.46532826,  0.42999785, ...,  1.62826949,
         0.58650534,  1.92985861],
       [-0.8198701 , -0.88371381, -0.77433164, ..., -0.48632074,
        -1.27456515,  1.1093665 ]])

In [22]:
y_train

408    M
285    B
1      M
269    B
540    B
      ..
198    M
374    B
71     B
257    M
388    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [23]:
#Since y has output in alphabet, we need to encode it into numeric values.
encoding = LabelEncoder()
y_train = encoding.fit_transform(y_train)
y_test = encoding.transform(y_test)

In [24]:
y_train

array([1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0])

NumPy to PyTorch

In [25]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [26]:
x_train_tensor.shape

torch.Size([455, 30])

In [27]:
y_train_tensor.shape

torch.Size([455])

Define Model

In [28]:
class MySimpleNN():

  def __init__(self, x):

    self.weights = torch.rand(x.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

  def forward(self, x):
      z = torch.matmul(x , self.weights) + self.bias
      y_predicted = torch.sigmoid(z)
      return y_predicted

    #one of the possible approaches
    #def loss(self, y_predicted, y):
    #  loss = torch.mean((y - y_predicted))**2

  def loss_function(self, y_predicted, y):
      #clamp predictions to avoid log(0)
      epsilon = 1e-7
      y_predicted = torch.clamp(y_predicted, epsilon, 1-epsilon)

      #calculate loss
      loss = -(y_train_tensor * torch.log(y_predicted) + (1 - y_train_tensor) * torch.log(1 - y_predicted)).mean()
      return loss

Important parameters

In [29]:
learning_rate = 0.1
epochs = 25

Traning pipeline

In [30]:
# create model
model = MySimpleNN(x_train_tensor)

#define loop
for epoch in range(epochs):

  #forward pass
  y_predicted = model.forward(x_train_tensor)

  #calculate loss
  loss = model.loss_function(y_predicted, y_train_tensor)

  #backward pass
  loss.backward()

  #update parameters
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  #zero gradient initialize
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 3.855012970787542
Epoch: 2, Loss: 3.726543965869167
Epoch: 3, Loss: 3.59068317976603
Epoch: 4, Loss: 3.4550984627448638
Epoch: 5, Loss: 3.3124469389832583
Epoch: 6, Loss: 3.169265083951481
Epoch: 7, Loss: 3.0221943261877855
Epoch: 8, Loss: 2.8678993370313357
Epoch: 9, Loss: 2.713030146754175
Epoch: 10, Loss: 2.5503570654246346
Epoch: 11, Loss: 2.3807313655181144
Epoch: 12, Loss: 2.2138911523476343
Epoch: 13, Loss: 2.045280839765285
Epoch: 14, Loss: 1.88242899909524
Epoch: 15, Loss: 1.7241592331080247
Epoch: 16, Loss: 1.5702176436675306
Epoch: 17, Loss: 1.4241092310023946
Epoch: 18, Loss: 1.293251306932468
Epoch: 19, Loss: 1.1793451175323149
Epoch: 20, Loss: 1.08345846217495
Epoch: 21, Loss: 1.0056313393575471
Epoch: 22, Loss: 0.9446645032281149
Epoch: 23, Loss: 0.8982661861750445
Epoch: 24, Loss: 0.8635419421159958
Epoch: 25, Loss: 0.8375939652430578

In [31]:
model.weights

tensor([[-0.1923],
        [ 0.3483],
        [-0.3033],
        [ 0.2873],
        [ 0.0836],
        [-0.0461],
        [ 0.1327],
        [-0.0494],
        [ 0.3793],
        [ 0.6063],
        [-0.3115],
        [-0.0633],
        [ 0.3985],
        [ 0.0351],
        [ 0.1804],
        [-0.0395],
        [-0.1024],
        [ 0.2230],
        [ 0.5059],
        [-0.2936],
        [ 0.4605],
        [ 0.1170],
        [-0.2720],
        [ 0.2847],
        [-0.2402],
        [ 0.0500],
        [ 0.1964],
        [-0.5885],
        [ 0.1332],
        [-0.3520]], dtype=torch.float64, requires_grad=True)

In [32]:
model.bias

tensor([-0.0919], dtype=torch.float64, requires_grad=True)

Evaluation

In [33]:
with torch.no_grad():
  y_prediction = model.forward(x_test_tensor)
  y_prediction = (y_prediction > 0.95).float()
  accuracy = (y_prediction == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.671283483505249