<a href="https://colab.research.google.com/github/AryanRaut14/NeuralNetworkfromScratch/blob/nn_module/NeuralNetworkUsingNNModule.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/AryanRaut14/BreastCancerDetection/main/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [3]:
df.shape

(569, 33)

In [4]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [5]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Train Test Split

In [6]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Scaling

In [7]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [8]:
x_train

array([[-0.09697241, -0.47756264, -0.16171188, ..., -0.98153886,
        -0.84805069, -0.7014467 ],
       [-0.76422435, -0.45442294, -0.75291274, ..., -0.78506889,
        -0.50862967, -0.17414031],
       [ 0.72744217,  0.04308052,  0.63668928, ..., -0.47719529,
        -0.59657057, -1.39952189],
       ...,
       [-1.31401789, -0.22071201, -1.30651355, ..., -0.98940977,
        -0.70919664, -0.15106345],
       [-0.70632232, -0.21839804, -0.69251265, ...,  0.08951009,
        -0.16612302,  0.40335826],
       [-0.6484203 , -0.4197134 , -0.67771263, ..., -0.37063531,
         0.2890097 , -0.80240799]])

In [9]:
y_train

125    B
142    B
157    B
467    B
324    B
      ..
26     M
224    B
359    B
106    B
293    B
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [10]:
#Since y has output in alphabet, we need to encode it into numeric values.
encoding = LabelEncoder()
y_train = encoding.fit_transform(y_train)
y_test = encoding.transform(y_test)

In [11]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

NumPy to PyTorch

In [53]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)

In [54]:
x_train_tensor.shape

torch.Size([455, 30])

In [55]:
y_train_tensor.shape

torch.Size([455, 1])

Define Model

In [56]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
      out = self.linear(features)
      out = self.sigmoid(out)
      return out

  def loss_function(self, y_predicted, y_true):
    return nn.BCELoss()(y_predicted, y_true)

Important parameters

In [57]:
learning_rate = 0.1
epochs = 25

In [66]:
# define loss function
#binary cross entropy loss
loss_function = nn.BCELoss()

Traning pipeline

In [68]:
# create model
n = x_train_tensor.shape[1]
model = MySimpleNN(n).float()

#define loop
for epoch in range(epochs):

  #forward pass
  y_predicted = model(x_train_tensor)

  #calculate loss
  loss = loss_function(y_predicted, y_train_tensor.view(-1,1))

  #backward pass
  loss.backward()

  #update parameters
  with torch.no_grad():
    model.linear.weight -= learning_rate * model.linear.weight.grad
    model.linear.bias -= learning_rate * model.linear.bias.grad

  #zero gradient initialize
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  #print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6239893436431885
Epoch: 2, Loss: 0.4871155321598053
Epoch: 3, Loss: 0.4128601551055908
Epoch: 4, Loss: 0.3661119043827057
Epoch: 5, Loss: 0.33346933126449585
Epoch: 6, Loss: 0.3090609014034271
Epoch: 7, Loss: 0.2899206578731537
Epoch: 8, Loss: 0.2743833661079407
Epoch: 9, Loss: 0.2614363431930542
Epoch: 10, Loss: 0.2504250407218933
Epoch: 11, Loss: 0.2409055233001709
Epoch: 12, Loss: 0.23256483674049377
Epoch: 13, Loss: 0.2251754105091095
Epoch: 14, Loss: 0.21856720745563507
Epoch: 15, Loss: 0.21261030435562134
Epoch: 16, Loss: 0.20720353722572327
Epoch: 17, Loss: 0.20226670801639557
Epoch: 18, Loss: 0.1977352797985077
Epoch: 19, Loss: 0.19355668127536774
Epoch: 20, Loss: 0.18968762457370758
Epoch: 21, Loss: 0.18609187006950378
Epoch: 22, Loss: 0.1827390044927597
Epoch: 23, Loss: 0.17960315942764282
Epoch: 24, Loss: 0.17666226625442505
Epoch: 25, Loss: 0.17389723658561707

In [69]:
model.linear.weight

Parameter containing:
tensor([[ 0.1550,  0.1301,  0.1858,  0.3470,  0.1218,  0.1510,  0.3018,  0.2935,
          0.0804, -0.0520,  0.1460,  0.0329,  0.0735,  0.0263, -0.0265,  0.0569,
         -0.0374,  0.1362, -0.0725, -0.1724,  0.3681,  0.3246,  0.2952,  0.2006,
          0.0260,  0.3106,  0.2001,  0.1997,  0.1948, -0.0535]],
       requires_grad=True)

In [70]:
model.linear.bias

Parameter containing:
tensor([-0.1009], requires_grad=True)

Evaluation

In [71]:
with torch.no_grad():
  y_prediction = model.forward(x_test_tensor)
  y_prediction = (y_prediction > 0.95).float()
  accuracy = (y_prediction == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.859649121761322