<a href="https://colab.research.google.com/github/AryanRaut14/NeuralNetworkfromScratch/blob/datasetanddataloaderclass/NeuralNetworkDatasetandDataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [51]:
df = pd.read_csv('https://raw.githubusercontent.com/AryanRaut14/BreastCancerDetection/main/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [52]:
df.shape

(569, 33)

In [53]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [54]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

Train Test Split

In [55]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Scaling

In [56]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [57]:
x_train

array([[-1.56400412, -1.73833583, -1.54984813, ..., -1.0691607 ,
         0.52579614,  0.35372932],
       [ 0.17718293, -0.55366235,  0.12076076, ..., -0.54845526,
        -0.73204052, -1.08040838],
       [ 0.88267884,  1.85782716,  0.83266558, ...,  0.6310365 ,
         0.18050765,  0.37379545],
       ...,
       [-0.71914385, -1.98884979, -0.73737995, ..., -1.02394838,
         0.8053154 , -0.58583744],
       [-0.53120436, -1.38714804, -0.51320745, ..., -0.49362004,
         0.93520964,  0.48061805],
       [ 3.23625948,  1.33338672,  3.3593201 , ...,  2.6350422 ,
        -0.89646361,  1.22955662]])

In [58]:
y_train

59     B
486    B
460    M
329    M
382    B
      ..
344    B
107    B
313    B
130    B
82     M
Name: diagnosis, Length: 455, dtype: object

Label Encoding

In [59]:
#Since y has output in alphabet, we need to encode it into numeric values.
encoding = LabelEncoder()
y_train = encoding.fit_transform(y_train)
y_test = encoding.transform(y_test)

In [60]:
y_train

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1])

NumPy to PyTorch

In [61]:
x_train_tensor = torch.from_numpy(x_train).float()
x_test_tensor = torch.from_numpy(x_test).float()
y_train_tensor = torch.from_numpy(y_train).float().unsqueeze(1)
y_test_tensor = torch.from_numpy(y_test).float().unsqueeze(1)

In [62]:
x_train_tensor.shape

torch.Size([455, 30])

In [63]:
y_train_tensor.shape

torch.Size([455, 1])

Implement Dataset and DataLoader

In [64]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return len(self.features)

  def __getitem__(self, idx):

    return self.features[idx], self.labels[idx]

In [65]:
train_dataset = CustomDataset(x_train_tensor, y_train_tensor)
test_dataset = CustomDataset(x_test_tensor, y_test_tensor)

In [66]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=True)

Define Model

In [67]:
import torch.nn as nn

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
      out = self.linear(features)
      out = self.sigmoid(out)
      return out

  def loss_function(self, y_predicted, y_true):
    return nn.BCELoss()(y_predicted, y_true)

Important parameters

In [68]:
learning_rate = 0.1
epochs = 25

In [69]:
# define loss function
#binary cross entropy loss
loss_function = nn.BCELoss()

Traning pipeline

In [70]:
# create model
n = x_train_tensor.shape[1]
model = MySimpleNN(n).float()

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# training loop
for epoch in range(epochs):
    epoch_loss = 0
    for batch_features, batch_labels in train_loader:
        # forward pass using the current batch
        y_predicted = model(batch_features)

        # calculate loss for the current batch
        loss = loss_function(y_predicted, batch_labels)

        # clear gradient
        optimizer.zero_grad()

        # backward pass
        loss.backward()

        # update parameters
        optimizer.step()

        epoch_loss += loss.item()

    # print average loss in each epoch
    if (epoch + 1) % 5 == 0:
        print(f'Epoch: {epoch + 1}, Avg Loss: {epoch_loss / len(train_loader):.4f}')

Epoch: 1, Loss: 0.2091132551431656
Epoch: 2, Loss: 0.15825104713439941
Epoch: 3, Loss: 0.1361573189496994
Epoch: 4, Loss: 0.12319730967283249
Epoch: 5, Loss: 0.11447028815746307
Epoch: 6, Loss: 0.10810358822345734
Epoch: 7, Loss: 0.10320861637592316
Epoch: 8, Loss: 0.09930253773927689
Epoch: 9, Loss: 0.09609757363796234
Epoch: 10, Loss: 0.09341010451316833
Epoch: 11, Loss: 0.09111693501472473
Epoch: 12, Loss: 0.08913187682628632
Epoch: 13, Loss: 0.08739273250102997
Epoch: 14, Loss: 0.08585331588983536
Epoch: 15, Loss: 0.08447861671447754
Epoch: 16, Loss: 0.08324150741100311
Epoch: 17, Loss: 0.08212066441774368
Epoch: 18, Loss: 0.08109905570745468
Epoch: 19, Loss: 0.08016292750835419
Epoch: 20, Loss: 0.07930098474025726
Epoch: 21, Loss: 0.07850392162799835
Epoch: 22, Loss: 0.07776395231485367
Epoch: 23, Loss: 0.0770745649933815
Epoch: 24, Loss: 0.07643018662929535
Epoch: 25, Loss: 0.07582607865333557

Evaluation

In [71]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        # Standard threshold for Sigmoid is 0.5, not 0.8
        y_pred_class = (y_pred > 0.5).float()

        # Calculate accuracy for the current batch
        # Ensure labels are flattened to match y_pred_class shape
        batch_accuracy = (y_pred_class.view(-1) == batch_labels.view(-1)).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')

Accuracy: 0.9922